### ISSUE TITLE
Editing an existing test and saving results in unavoidable error-message

### ISSUE THREAD

**Issue by madskonradsen** [jsperf/jsperf.com#129]
...saying: "Please review required fields and save again." no matter fields contains content

**Comment by madskonradsen** [comment]
Exception happens here: https://github.com/jsperf/jsperf.com/blob/68f102d62923866dca973cb6ac0939b24bc84661/server/web/edit/index.js#L81

**Comment by madskonradsen** [comment]
It seems odd that it won't validate... i guess the unit-tests would have caught any issues with changes to the schema?

**Comment by maxbeatty** [comment]
should be fixed by #143 but there are still other issues with editing that have not been resolved

**Comment by krisnye** [comment]
This is still happening on the live site as of today. Nov 20, 2016.

**Comment by bendilts** [comment]
Still happening.

**Comment by maxbeatty** [comment]
"still happening" is... good I guess 
[comments with details](https://github.com/jsperf/jsperf.com/issues/129#issuecomment-231839117) are much better
**pull requests are best**

**Comment by bnmbnmbnmbnm** [comment]
Still happening.

**Comment by madskonradsen** [comment]
Less complaining, more PRs

**Comment by ryan-copperleaf** [comment]
Please reopen this, as it’s still happening.

**Comment by marvin-martian** [comment]
^ Ditto

**Comment by olvenmage** [comment]
Again..

**Comment by madskonradsen** [comment]
Consider opening a new issue, or even better, a PR.

**Comment by 3DEsprit** [comment]
In my recent issue with this error, there was a typo in my GitHub website URL, giving a 400 error. Once I fixed the URL the error went away. Not quite sure why the URL is being checked though.

**Comment by destructive-dragon** [comment]
Would be great if this could be fixed. I checked all my data 10x and still don't have any clue why the error happens.

**Comment by rodrigograca31** [comment]
Still having this issue. Just like @destructive-dragon I checked everything and theres nothing obvious missing

**Comment by Spongman** [comment]
still happening...

**Comment by Qix-** [comment]
Still happening.

**Comment by Fire-** [comment]
It would be nice if he error produced was more specific in regard to which field needs work. I can't save anything and I'm not sure if it's because something is wrong with the test page, or if jsperf can't handle the dash in my github username somehow.
